# DO NOT EDIT — generated by scripts/generate_sdk_scope_constants.py
# Source: docs/platform/scopes.yaml + docs/platform/roles.yaml
# Regenerate via `python3 scripts/generate_sdk_scope_constants.py`.

from typing import Final

class OlympusRoles:
    """Every role in the Olympus Cloud platform catalog."""
    #: Break-glass root. Emergency-only. All platform scopes.
    SUPER_ADMIN: Final[str] = 'super_admin'
    #: System-level administrative access across all tenants. Used by internal SREs.
    SYSTEM_ADMIN: Final[str] = 'system_admin'
    #: Day-to-day platform operations — tenant CRUD, app install review, HITL approvals.
    PLATFORM_OPERATOR: Final[str] = 'platform_operator'
    #: Platform administrative role for product + developer-experience operations.
    PLATFORM_ADMIN: Final[str] = 'platform_admin'
    #: Full control of a single tenant — user management, app installs, billing, settings.
    TENANT_ADMIN: Final[str] = 'tenant_admin'
    #: Tenant billing/legal owner. Often same person as tenant_admin but tracked separately for compliance.
    TENANT_OWNER: Final[str] = 'tenant_owner'
    #: Operational manager within a tenant — staff management, reporting, non-billing settings.
    MANAGER: Final[str] = 'manager'
    #: Shift supervisor — can approve overrides, adjust orders, view team reports.
    SUPERVISOR: Final[str] = 'supervisor'
    #: Line-level staff — POS, kitchen, counter. Read-only on reports by default.
    STAFF: Final[str] = 'staff'
    #: Baseline tenant-attached identity with no operational role. Customers, guests, invited users before role assignment.
    USER: Final[str] = 'user'
    #: Restaurant GM/FOH-manager — menu, staff, reservations, POS overrides.
    RESTAURANT_MANAGER: Final[str] = 'restaurant_manager'
    #: Bar-vertical staff — dram-shop compliance, age verification workflows.
    BARTENDER: Final[str] = 'bartender'
    #: Delivery driver — route/order assignment, geofence pickup.
    DRIVER: Final[str] = 'driver'
    #: Admin of an installed app's own configuration (app-level settings, not tenant settings).
    APP_ADMIN: Final[str] = 'app_admin'
    #: Baseline user interacting with an installed app without admin powers.
    APP_USER: Final[str] = 'app_user'
    #: Device principal (POS terminal, kiosk, KDS). Subject format `device:<uuid>`. Calls are bounded to registered device surface.
    DEVICE: Final[str] = 'device'

OLYMPUS_ROLES_ALL: Final[tuple[str, ...]] = (
    'super_admin',
    'system_admin',
    'platform_operator',
    'platform_admin',
    'tenant_admin',
    'tenant_owner',
    'manager',
    'supervisor',
    'staff',
    'user',
    'restaurant_manager',
    'bartender',
    'driver',
    'app_admin',
    'app_user',
    'device',
)

#: Roles that grant global platform control. Matches `backend/rust/platform/src/middleware/rbac.rs:PLATFORM_ADMIN_ROLES`.
PLATFORM_ADMIN_ROLES: Final[tuple[str, ...]] = (
    'platform_admin',
    'platform_operator',
    'system_admin',
    'super_admin',
)

#: Roles that can manage tenant-scoped resources. Matches `TENANT_ADMIN_ROLES` in Rust middleware.
TENANT_ADMIN_ROLES: Final[tuple[str, ...]] = (
    'tenant_admin',
    'tenant_owner',
    'platform_admin',
    'platform_operator',
    'system_admin',
    'super_admin',
)

#: Roles that can operate tenant resources (managers, supervisors, admins). Matches `TENANT_OPERATOR_ROLES` in Rust middleware.
TENANT_OPERATOR_ROLES: Final[tuple[str, ...]] = (
    'manager',
    'supervisor',
    'restaurant_manager',
    'tenant_admin',
    'tenant_owner',
    'platform_admin',
    'platform_operator',
    'system_admin',
    'super_admin',
)
