# DO NOT EDIT — generated by scripts/generate_sdk_scope_constants.py
# Source: docs/platform/scopes.yaml + docs/platform/roles.yaml
# Regenerate via `python3 scripts/generate_sdk_scope_constants.py`.

from typing import Final

class OlympusScopes:
    """Every scope in the Olympus Cloud platform catalog."""
    #: List the caller's active sessions.
    AUTH_SESSION_READ_AT_USER: Final[str] = 'auth.session.read@user'
    #: Revoke one of the caller's own sessions.
    AUTH_SESSION_DELETE_AT_USER: Final[str] = 'auth.session.delete@user'
    #: Enroll, update, or disable the caller's MFA factors.
    AUTH_MFA_WRITE_AT_USER: Final[str] = 'auth.mfa.write@user'
    #: Read the caller's tenant metadata (name, plan, hierarchy position).
    PLATFORM_TENANT_READ_AT_TENANT: Final[str] = 'platform.tenant.read@tenant'
    #: Update tenant-level settings (display name, locale, default brand).
    PLATFORM_TENANT_WRITE_AT_TENANT: Final[str] = 'platform.tenant.write@tenant'
    #: Grant/revoke tenant administrators, rotate tenant keys, close tenant.
    PLATFORM_TENANT_ADMIN_AT_TENANT: Final[str] = 'platform.tenant.admin@tenant'
    #: Read the caller's profile (name, email, avatar, preferences).
    PLATFORM_USER_PROFILE_READ_AT_USER: Final[str] = 'platform.user.profile.read@user'
    #: Update the caller's profile.
    PLATFORM_USER_PROFILE_WRITE_AT_USER: Final[str] = 'platform.user.profile.write@user'
    #: List users in the tenant.
    PLATFORM_USER_READ_AT_TENANT: Final[str] = 'platform.user.read@tenant'
    #: Invite or update users in the tenant.
    PLATFORM_USER_WRITE_AT_TENANT: Final[str] = 'platform.user.write@tenant'
    #: Remove a user from the tenant (soft-delete; GDPR-safe).
    PLATFORM_USER_DELETE_AT_TENANT: Final[str] = 'platform.user.delete@tenant'
    #: List brands within the tenant.
    PLATFORM_BRAND_READ_AT_TENANT: Final[str] = 'platform.brand.read@tenant'
    #: Create or update brands within the tenant.
    PLATFORM_BRAND_WRITE_AT_TENANT: Final[str] = 'platform.brand.write@tenant'
    #: List locations within the tenant.
    PLATFORM_LOCATION_READ_AT_TENANT: Final[str] = 'platform.location.read@tenant'
    #: Create or update locations.
    PLATFORM_LOCATION_WRITE_AT_TENANT: Final[str] = 'platform.location.write@tenant'
    #: Pair a device to the authenticated user for PIN-only subsequent logins.
    PLATFORM_DEVICE_AUTHORIZE_EXECUTE_AT_USER: Final[str] = 'platform.device.authorize.execute@user'
    #: Revoke a device binding for the authenticated user.
    PLATFORM_DEVICE_UNBIND_DELETE_AT_USER: Final[str] = 'platform.device.unbind.delete@user'
    #: Read orders for the tenant.
    COMMERCE_ORDER_READ_AT_TENANT: Final[str] = 'commerce.order.read@tenant'
    #: Create or update orders.
    COMMERCE_ORDER_WRITE_AT_TENANT: Final[str] = 'commerce.order.write@tenant'
    #: Void or cancel orders.
    COMMERCE_ORDER_DELETE_AT_TENANT: Final[str] = 'commerce.order.delete@tenant'
    #: Read customer records.
    COMMERCE_CUSTOMER_READ_AT_TENANT: Final[str] = 'commerce.customer.read@tenant'
    #: Create or update customer records.
    COMMERCE_CUSTOMER_WRITE_AT_TENANT: Final[str] = 'commerce.customer.write@tenant'
    #: Read inventory levels.
    COMMERCE_INVENTORY_READ_AT_TENANT: Final[str] = 'commerce.inventory.read@tenant'
    #: Adjust inventory.
    COMMERCE_INVENTORY_WRITE_AT_TENANT: Final[str] = 'commerce.inventory.write@tenant'
    #: Read product catalog.
    COMMERCE_CATALOG_READ_AT_TENANT: Final[str] = 'commerce.catalog.read@tenant'
    #: Create or update products.
    COMMERCE_CATALOG_WRITE_AT_TENANT: Final[str] = 'commerce.catalog.write@tenant'
    #: Invoke AI inference against the Ether router (chat, completion, embed).
    AI_INFERENCE_EXECUTE_AT_TENANT: Final[str] = 'ai.inference.execute@tenant'
    #: Invoke an Ether-managed agent (Pantheon or custom).
    AI_AGENT_EXECUTE_AT_TENANT: Final[str] = 'ai.agent.execute@tenant'
    #: Manage tenant-level AI model configuration (custom tiers, routing overrides).
    AI_MODEL_ADMIN_AT_TENANT: Final[str] = 'ai.model.admin@tenant'
    #: Read payment records.
    PAY_PAYMENT_READ_AT_TENANT: Final[str] = 'pay.payment.read@tenant'
    #: Initiate payment captures.
    PAY_PAYMENT_WRITE_AT_TENANT: Final[str] = 'pay.payment.write@tenant'
    #: Issue refunds for captured payments.
    PAY_REFUND_EXECUTE_AT_TENANT: Final[str] = 'pay.refund.execute@tenant'
    #: Read payout records.
    PAY_PAYOUT_READ_AT_TENANT: Final[str] = 'pay.payout.read@tenant'
    #: Send transactional emails through Olympus Notify.
    NOTIFY_EMAIL_WRITE_AT_TENANT: Final[str] = 'notify.email.write@tenant'
    #: Send SMS messages.
    NOTIFY_SMS_WRITE_AT_TENANT: Final[str] = 'notify.sms.write@tenant'
    #: Send push notifications.
    NOTIFY_PUSH_WRITE_AT_TENANT: Final[str] = 'notify.push.write@tenant'
    #: Register/deregister FCM device tokens for the authenticated user.
    NOTIFY_DEVICES_WRITE_AT_USER: Final[str] = 'notify.devices.write@user'
    #: Subscribe the authenticated user's devices to public notification topics.
    NOTIFY_TOPICS_SUBSCRIBE_AT_USER: Final[str] = 'notify.topics.subscribe@user'
    #: Subscribe arbitrary users/devices to privileged topics (e.g. role-gated topics).
    NOTIFY_TOPICS_ADMIN_AT_TENANT: Final[str] = 'notify.topics.admin@tenant'
    #: Read domain events from the tenant's event stream.
    EVENTS_STREAM_READ_AT_TENANT: Final[str] = 'events.stream.read@tenant'
    #: Publish domain events.
    EVENTS_STREAM_WRITE_AT_TENANT: Final[str] = 'events.stream.write@tenant'
    #: Execute declarative queries against the tenant's data surface.
    DATA_QUERY_EXECUTE_AT_TENANT: Final[str] = 'data.query.execute@tenant'
    #: Read pre-computed analytics cubes.
    DATA_CUBE_READ_AT_TENANT: Final[str] = 'data.cube.read@tenant'
    #: Read files in tenant R2 buckets.
    STORAGE_FILE_READ_AT_TENANT: Final[str] = 'storage.file.read@tenant'
    #: Upload or replace files.
    STORAGE_FILE_WRITE_AT_TENANT: Final[str] = 'storage.file.write@tenant'
    #: Delete files.
    STORAGE_FILE_DELETE_AT_TENANT: Final[str] = 'storage.file.delete@tenant'
    #: Read marketplace listings.
    MARKETPLACE_LISTING_READ_AT_TENANT: Final[str] = 'marketplace.listing.read@tenant'
    #: Install or remove apps from the marketplace.
    MARKETPLACE_INSTALL_WRITE_AT_TENANT: Final[str] = 'marketplace.install.write@tenant'
    #: Read active subscriptions.
    BILLING_SUBSCRIPTION_READ_AT_TENANT: Final[str] = 'billing.subscription.read@tenant'
    #: Change subscription plan, add-ons, or quantity.
    BILLING_SUBSCRIPTION_WRITE_AT_TENANT: Final[str] = 'billing.subscription.write@tenant'
    #: Read invoices.
    BILLING_INVOICE_READ_AT_TENANT: Final[str] = 'billing.invoice.read@tenant'
    #: Read feature-gating policies.
    GATING_POLICY_READ_AT_TENANT: Final[str] = 'gating.policy.read@tenant'
    #: Write feature-gating overrides.
    GATING_POLICY_WRITE_AT_TENANT: Final[str] = 'gating.policy.write@tenant'
    #: Read registered kiosks.
    DEVICES_KIOSK_READ_AT_TENANT: Final[str] = 'devices.kiosk.read@tenant'
    #: Register, configure, or pair kiosks.
    DEVICES_KIOSK_WRITE_AT_TENANT: Final[str] = 'devices.kiosk.write@tenant'
    #: Register or reconfigure printers.
    DEVICES_PRINTER_WRITE_AT_TENANT: Final[str] = 'devices.printer.write@tenant'
    #: Register cameras and configure vision pipelines.
    DEVICES_CAMERA_ADMIN_AT_TENANT: Final[str] = 'devices.camera.admin@tenant'
    #: Read observability logs scoped to the tenant.
    OBSERVE_LOG_READ_AT_TENANT: Final[str] = 'observe.log.read@tenant'
    #: Read metrics.
    OBSERVE_METRIC_READ_AT_TENANT: Final[str] = 'observe.metric.read@tenant'
    #: Create or update alert rules.
    OBSERVE_ALERT_WRITE_AT_TENANT: Final[str] = 'observe.alert.write@tenant'
    #: Read call records (metadata only, not transcripts).
    VOICE_CALL_READ_AT_TENANT: Final[str] = 'voice.call.read@tenant'
    #: Place or modify voice calls.
    VOICE_CALL_WRITE_AT_TENANT: Final[str] = 'voice.call.write@tenant'
    #: Read call transcripts.
    VOICE_TRANSCRIPT_READ_AT_TENANT: Final[str] = 'voice.transcript.read@tenant'
    #: Provision, port, or release voice numbers.
    VOICE_NUMBER_ADMIN_AT_TENANT: Final[str] = 'voice.number.admin@tenant'
    #: Configure voice agents (pipeline, prompts, fallback).
    VOICE_AGENT_ADMIN_AT_TENANT: Final[str] = 'voice.agent.admin@tenant'
    #: Read agent-workflow runs.
    WORKFLOWS_RUN_READ_AT_TENANT: Final[str] = 'workflows.run.read@tenant'
    #: Trigger agent-workflow runs.
    WORKFLOWS_RUN_EXECUTE_AT_TENANT: Final[str] = 'workflows.run.execute@tenant'
    #: Create or update workflow definitions.
    WORKFLOWS_DEFINITION_WRITE_AT_TENANT: Final[str] = 'workflows.definition.write@tenant'
    #: Read leads.
    CONNECT_LEAD_READ_AT_TENANT: Final[str] = 'connect.lead.read@tenant'
    #: Create or update leads.
    CONNECT_LEAD_WRITE_AT_TENANT: Final[str] = 'connect.lead.write@tenant'
    #: Read opportunities / deals.
    CONNECT_OPPORTUNITY_READ_AT_TENANT: Final[str] = 'connect.opportunity.read@tenant'
    #: Create or update opportunities.
    CONNECT_OPPORTUNITY_WRITE_AT_TENANT: Final[str] = 'connect.opportunity.write@tenant'
    #: Read external-IDP configuration.
    IDENTITY_FEDERATION_READ_AT_TENANT: Final[str] = 'identity.federation.read@tenant'
    #: Configure SSO, SCIM, or external-IDP settings.
    IDENTITY_FEDERATION_ADMIN_AT_TENANT: Final[str] = 'identity.federation.admin@tenant'
    #: Read camera analytics (counts, dwell time, events).
    VISION_ANALYTICS_READ_AT_TENANT: Final[str] = 'vision.analytics.read@tenant'
    #: Run recognition models against camera feeds.
    VISION_RECOGNITION_EXECUTE_AT_TENANT: Final[str] = 'vision.recognition.execute@tenant'
    #: Read message threads in the tenant's inbox.
    MESSAGES_THREAD_READ_AT_TENANT: Final[str] = 'messages.thread.read@tenant'
    #: Send messages on behalf of the tenant.
    MESSAGES_THREAD_WRITE_AT_TENANT: Final[str] = 'messages.thread.write@tenant'
    #: Read the caller's own inbox.
    MESSAGES_INBOX_READ_AT_USER: Final[str] = 'messages.inbox.read@user'
    #: Forward-geocode a street address to lat/lng coordinates.
    MAPS_GEOCODE_READ_AT_APP: Final[str] = 'maps.geocode.read@app'
    #: Reverse-geocode lat/lng coordinates (often from user device) to an address.
    MAPS_REVERSE_GEOCODE_READ_AT_TENANT: Final[str] = 'maps.reverse_geocode.read@tenant'
    #: Validate whether an address or coordinate falls within configured delivery zones.
    MAPS_DELIVERY_ZONE_EXECUTE_AT_TENANT: Final[str] = 'maps.delivery_zone.execute@tenant'
    #: Build a provider-specific directions URL (Waze / Google Maps / Apple Maps / OSM).
    MAPS_DIRECTIONS_URL_READ_AT_APP: Final[str] = 'maps.directions_url.read@app'
    #: Read POS register state.
    POS_REGISTER_READ_AT_TENANT: Final[str] = 'pos.register.read@tenant'
    #: Record POS transactions.
    POS_TRANSACTION_WRITE_AT_TENANT: Final[str] = 'pos.transaction.write@tenant'
    #: Submit voice-originated orders to the POS.
    POS_VOICE_ORDER_EXECUTE_AT_TENANT: Final[str] = 'pos.voice_order.execute@tenant'
    #: Read ad campaigns.
    ADS_CAMPAIGN_READ_AT_TENANT: Final[str] = 'ads.campaign.read@tenant'
    #: Create or update ad campaigns.
    ADS_CAMPAIGN_WRITE_AT_TENANT: Final[str] = 'ads.campaign.write@tenant'
    #: Read developer app records owned by the tenant.
    DEVELOPER_APP_READ_AT_TENANT: Final[str] = 'developer.app.read@tenant'
    #: Submit, update, or publish developer apps.
    DEVELOPER_APP_ADMIN_AT_TENANT: Final[str] = 'developer.app.admin@tenant'
    #: Read the caller's health/wellness records.
    HEALTH_RECORD_READ_AT_USER: Final[str] = 'health.record.read@user'
    #: Add to the caller's health records.
    HEALTH_RECORD_WRITE_AT_USER: Final[str] = 'health.record.write@user'
    #: Read the PizzaOS menu (items, categories, modifiers, price history).
    PIZZA_MENU_READ_AT_TENANT: Final[str] = 'pizza.menu.read@tenant'
    #: Create or update menu items.
    PIZZA_MENU_WRITE_AT_TENANT: Final[str] = 'pizza.menu.write@tenant'
    #: Read pizza orders.
    PIZZA_ORDERS_READ_AT_TENANT: Final[str] = 'pizza.orders.read@tenant'
    #: Create or update pizza orders.
    PIZZA_ORDERS_WRITE_AT_TENANT: Final[str] = 'pizza.orders.write@tenant'
    #: Issue refunds / void completed orders (hits pay.refund + commerce.cancelOrder).
    PIZZA_ORDERS_REFUND_AT_TENANT: Final[str] = 'pizza.orders.refund@tenant'
    #: Read pizza customer records.
    PIZZA_CUSTOMERS_READ_AT_TENANT: Final[str] = 'pizza.customers.read@tenant'
    #: Create or update customer records (addresses, caller-ID matches, notes).
    PIZZA_CUSTOMERS_WRITE_AT_TENANT: Final[str] = 'pizza.customers.write@tenant'
    #: Read delivery zones.
    PIZZA_DELIVERY_ZONES_READ_AT_TENANT: Final[str] = 'pizza.delivery_zones.read@tenant'
    #: Update delivery zones.
    PIZZA_DELIVERY_ZONES_WRITE_AT_TENANT: Final[str] = 'pizza.delivery_zones.write@tenant'
    #: Read operating hours (consumed by menu board + customer app + phone-order flow).
    PIZZA_HOURS_READ_AT_TENANT: Final[str] = 'pizza.hours.read@tenant'
    #: Update operating hours.
    PIZZA_HOURS_WRITE_AT_TENANT: Final[str] = 'pizza.hours.write@tenant'
    #: Read loyalty program state (customer points, tiers, rewards).
    PIZZA_LOYALTY_READ_AT_TENANT: Final[str] = 'pizza.loyalty.read@tenant'
    #: Adjust loyalty balances and rules.
    PIZZA_LOYALTY_WRITE_AT_TENANT: Final[str] = 'pizza.loyalty.write@tenant'
    #: Read deals / promos (BOGO, % off, $ off, combos, time-window, day-of-week).
    PIZZA_DEALS_READ_AT_TENANT: Final[str] = 'pizza.deals.read@tenant'
    #: Create or update deals + coupon codes.
    PIZZA_DEALS_WRITE_AT_TENANT: Final[str] = 'pizza.deals.write@tenant'
    #: Administer deal budgets, redemption caps, corp-mandated deals (requires franchise trust).
    PIZZA_DEALS_ADMIN_AT_TENANT: Final[str] = 'pizza.deals.admin@tenant'
    #: Read driver roster + current GPS/assignment state.
    PIZZA_DRIVERS_READ_AT_TENANT: Final[str] = 'pizza.drivers.read@tenant'
    #: Dispatch drivers, update assignments, record deliveries.
    PIZZA_DRIVERS_WRITE_AT_TENANT: Final[str] = 'pizza.drivers.write@tenant'
    #: Read KDS ticket queue, oven slot tracking, bump events.
    PIZZA_KITCHEN_READ_AT_TENANT: Final[str] = 'pizza.kitchen.read@tenant'
    #: Bump tickets, update oven slots, invoke prep-forecast agent.
    PIZZA_KITCHEN_WRITE_AT_TENANT: Final[str] = 'pizza.kitchen.write@tenant'
    #: Read owner analytics — food cost, labor %, review aggregates, demand anomalies (aggregated).
    PIZZA_REPORTS_READ_AT_TENANT: Final[str] = 'pizza.reports.read@tenant'
    #: Read operational inventory state (86 list, waste log, real-time counts).
    PIZZA_INVENTORY_READ_AT_TENANT: Final[str] = 'pizza.inventory.read@tenant'
    #: Mark items 86, log waste, adjust real-time counts.
    PIZZA_INVENTORY_WRITE_AT_TENANT: Final[str] = 'pizza.inventory.write@tenant'
    #: Read aggregated review data (Google, Yelp, delivery platforms) + sentiment.
    PIZZA_REVIEWS_READ_AT_TENANT: Final[str] = 'pizza.reviews.read@tenant'
    #: Draft or post review responses on behalf of the tenant.
    PIZZA_REVIEWS_WRITE_AT_TENANT: Final[str] = 'pizza.reviews.write@tenant'
    #: Corporate franchise administration over location-tenants within the same company. Cross-tenant access is authorized via policy-layer company_id check (JWT.company_id must match target tenant's company_id). No @org holder in 1.0 — company scoping lives in policy layer, not claim layer. See pizza-os#77 reply for design call.
    PIZZA_FRANCHISE_ADMIN_AT_TENANT: Final[str] = 'pizza.franchise.admin@tenant'
    #: Read OrderEchoAI orders (voice + chat originated).
    ORDERECHO_ORDER_READ_AT_TENANT: Final[str] = 'orderecho.order.read@tenant'
    #: Submit or update orders.
    ORDERECHO_ORDER_WRITE_AT_TENANT: Final[str] = 'orderecho.order.write@tenant'
    #: Cancel orders.
    ORDERECHO_ORDER_CANCEL_AT_TENANT: Final[str] = 'orderecho.order.cancel@tenant'
    #: Read the OrderEchoAI-managed menu projection.
    ORDERECHO_MENU_READ_AT_TENANT: Final[str] = 'orderecho.menu.read@tenant'
    #: Read customer profiles.
    ORDERECHO_CUSTOMER_READ_AT_TENANT: Final[str] = 'orderecho.customer.read@tenant'
    #: Collect payment for voice orders.
    ORDERECHO_PAYMENT_WRITE_AT_TENANT: Final[str] = 'orderecho.payment.write@tenant'
    #: Read voice transcripts captured by OrderEchoAI.
    ORDERECHO_VOICE_TRANSCRIPT_READ_AT_TENANT: Final[str] = 'orderecho.voice.transcript.read@tenant'
    #: Read the bar menu.
    BAR_MENU_READ_AT_TENANT: Final[str] = 'bar.menu.read@tenant'
    #: Update the bar menu.
    BAR_MENU_WRITE_AT_TENANT: Final[str] = 'bar.menu.write@tenant'
    #: Read open and closed tabs.
    BAR_TABS_READ_AT_TENANT: Final[str] = 'bar.tabs.read@tenant'
    #: Open, update, and close tabs.
    BAR_TABS_WRITE_AT_TENANT: Final[str] = 'bar.tabs.write@tenant'
    #: Void tabs (compliance-audited).
    BAR_TABS_VOID_AT_TENANT: Final[str] = 'bar.tabs.void@tenant'
    #: Read bar inventory.
    BAR_INVENTORY_READ_AT_TENANT: Final[str] = 'bar.inventory.read@tenant'
    #: Adjust bar inventory.
    BAR_INVENTORY_WRITE_AT_TENANT: Final[str] = 'bar.inventory.write@tenant'
    #: Update operating hours.
    BAR_HOURS_WRITE_AT_TENANT: Final[str] = 'bar.hours.write@tenant'
    #: Record age verification events for legal compliance.
    BAR_AGE_VERIFICATION_WRITE_AT_TENANT: Final[str] = 'bar.age_verification.write@tenant'
    #: Read bar loyalty program state.
    BAR_LOYALTY_READ_AT_TENANT: Final[str] = 'bar.loyalty.read@tenant'
    #: Adjust loyalty balances and rules.
    BAR_LOYALTY_WRITE_AT_TENANT: Final[str] = 'bar.loyalty.write@tenant'
    #: Update staff schedules.
    BAR_STAFF_SCHEDULE_WRITE_AT_TENANT: Final[str] = 'bar.staff.schedule.write@tenant'
    #: Submit voice-originated bar orders.
    BAR_VOICE_ORDER_EXECUTE_AT_TENANT: Final[str] = 'bar.voice.order.execute@tenant'
    #: Read the user's connected smart-home state.
    AURA_SMART_HOME_READ_AT_USER: Final[str] = 'aura.smart_home.read@user'
    #: Control smart-home devices.
    AURA_SMART_HOME_WRITE_AT_USER: Final[str] = 'aura.smart_home.write@user'
    #: Pair or remove smart-home devices and change automation rules.
    AURA_SMART_HOME_ADMIN_AT_USER: Final[str] = 'aura.smart_home.admin@user'
    #: Read the user's calendar.
    AURA_CALENDAR_READ_AT_USER: Final[str] = 'aura.calendar.read@user'
    #: Create or update calendar events.
    AURA_CALENDAR_WRITE_AT_USER: Final[str] = 'aura.calendar.write@user'
    #: Read the user's messages (email, SMS snippets).
    AURA_MESSAGES_READ_AT_USER: Final[str] = 'aura.messages.read@user'
    #: Read the user's current location.
    AURA_LOCATION_READ_AT_USER: Final[str] = 'aura.location.read@user'
    #: Execute voice commands on the user's behalf (may trigger smart-home actions).
    AURA_VOICE_COMMAND_EXECUTE_AT_USER: Final[str] = 'aura.voice.command.execute@user'
    #: Read the user's health and activity data.
    AURA_HEALTH_READ_AT_USER: Final[str] = 'aura.health.read@user'
    #: Post or schedule posts to the user's connected third-party social accounts (Twitter/X, Instagram, Facebook, etc.). Requested per maximus-ai#35 2026-04-18.
    AURA_SOCIAL_PUBLISH_AT_USER: Final[str] = 'aura.social.publish@user'
    #: Read CallStackAI call records.
    CALLSTACK_CALL_READ_AT_TENANT: Final[str] = 'callstack.call.read@tenant'
    #: Place or manage calls via CallStackAI.
    CALLSTACK_CALL_WRITE_AT_TENANT: Final[str] = 'callstack.call.write@tenant'
    #: Configure CallStack voice agents (prompts, escalation, on-call routing).
    CALLSTACK_AGENT_ADMIN_AT_TENANT: Final[str] = 'callstack.agent.admin@tenant'

OLYMPUS_SCOPES_ALL: Final[tuple[str, ...]] = (
    'auth.session.read@user',
    'auth.session.delete@user',
    'auth.mfa.write@user',
    'platform.tenant.read@tenant',
    'platform.tenant.write@tenant',
    'platform.tenant.admin@tenant',
    'platform.user.profile.read@user',
    'platform.user.profile.write@user',
    'platform.user.read@tenant',
    'platform.user.write@tenant',
    'platform.user.delete@tenant',
    'platform.brand.read@tenant',
    'platform.brand.write@tenant',
    'platform.location.read@tenant',
    'platform.location.write@tenant',
    'platform.device.authorize.execute@user',
    'platform.device.unbind.delete@user',
    'commerce.order.read@tenant',
    'commerce.order.write@tenant',
    'commerce.order.delete@tenant',
    'commerce.customer.read@tenant',
    'commerce.customer.write@tenant',
    'commerce.inventory.read@tenant',
    'commerce.inventory.write@tenant',
    'commerce.catalog.read@tenant',
    'commerce.catalog.write@tenant',
    'ai.inference.execute@tenant',
    'ai.agent.execute@tenant',
    'ai.model.admin@tenant',
    'pay.payment.read@tenant',
    'pay.payment.write@tenant',
    'pay.refund.execute@tenant',
    'pay.payout.read@tenant',
    'notify.email.write@tenant',
    'notify.sms.write@tenant',
    'notify.push.write@tenant',
    'notify.devices.write@user',
    'notify.topics.subscribe@user',
    'notify.topics.admin@tenant',
    'events.stream.read@tenant',
    'events.stream.write@tenant',
    'data.query.execute@tenant',
    'data.cube.read@tenant',
    'storage.file.read@tenant',
    'storage.file.write@tenant',
    'storage.file.delete@tenant',
    'marketplace.listing.read@tenant',
    'marketplace.install.write@tenant',
    'billing.subscription.read@tenant',
    'billing.subscription.write@tenant',
    'billing.invoice.read@tenant',
    'gating.policy.read@tenant',
    'gating.policy.write@tenant',
    'devices.kiosk.read@tenant',
    'devices.kiosk.write@tenant',
    'devices.printer.write@tenant',
    'devices.camera.admin@tenant',
    'observe.log.read@tenant',
    'observe.metric.read@tenant',
    'observe.alert.write@tenant',
    'voice.call.read@tenant',
    'voice.call.write@tenant',
    'voice.transcript.read@tenant',
    'voice.number.admin@tenant',
    'voice.agent.admin@tenant',
    'workflows.run.read@tenant',
    'workflows.run.execute@tenant',
    'workflows.definition.write@tenant',
    'connect.lead.read@tenant',
    'connect.lead.write@tenant',
    'connect.opportunity.read@tenant',
    'connect.opportunity.write@tenant',
    'identity.federation.read@tenant',
    'identity.federation.admin@tenant',
    'vision.analytics.read@tenant',
    'vision.recognition.execute@tenant',
    'messages.thread.read@tenant',
    'messages.thread.write@tenant',
    'messages.inbox.read@user',
    'maps.geocode.read@app',
    'maps.reverse_geocode.read@tenant',
    'maps.delivery_zone.execute@tenant',
    'maps.directions_url.read@app',
    'pos.register.read@tenant',
    'pos.transaction.write@tenant',
    'pos.voice_order.execute@tenant',
    'ads.campaign.read@tenant',
    'ads.campaign.write@tenant',
    'developer.app.read@tenant',
    'developer.app.admin@tenant',
    'health.record.read@user',
    'health.record.write@user',
    'pizza.menu.read@tenant',
    'pizza.menu.write@tenant',
    'pizza.orders.read@tenant',
    'pizza.orders.write@tenant',
    'pizza.orders.refund@tenant',
    'pizza.customers.read@tenant',
    'pizza.customers.write@tenant',
    'pizza.delivery_zones.read@tenant',
    'pizza.delivery_zones.write@tenant',
    'pizza.hours.read@tenant',
    'pizza.hours.write@tenant',
    'pizza.loyalty.read@tenant',
    'pizza.loyalty.write@tenant',
    'pizza.deals.read@tenant',
    'pizza.deals.write@tenant',
    'pizza.deals.admin@tenant',
    'pizza.drivers.read@tenant',
    'pizza.drivers.write@tenant',
    'pizza.kitchen.read@tenant',
    'pizza.kitchen.write@tenant',
    'pizza.reports.read@tenant',
    'pizza.inventory.read@tenant',
    'pizza.inventory.write@tenant',
    'pizza.reviews.read@tenant',
    'pizza.reviews.write@tenant',
    'pizza.franchise.admin@tenant',
    'orderecho.order.read@tenant',
    'orderecho.order.write@tenant',
    'orderecho.order.cancel@tenant',
    'orderecho.menu.read@tenant',
    'orderecho.customer.read@tenant',
    'orderecho.payment.write@tenant',
    'orderecho.voice.transcript.read@tenant',
    'bar.menu.read@tenant',
    'bar.menu.write@tenant',
    'bar.tabs.read@tenant',
    'bar.tabs.write@tenant',
    'bar.tabs.void@tenant',
    'bar.inventory.read@tenant',
    'bar.inventory.write@tenant',
    'bar.hours.write@tenant',
    'bar.age_verification.write@tenant',
    'bar.loyalty.read@tenant',
    'bar.loyalty.write@tenant',
    'bar.staff.schedule.write@tenant',
    'bar.voice.order.execute@tenant',
    'aura.smart_home.read@user',
    'aura.smart_home.write@user',
    'aura.smart_home.admin@user',
    'aura.calendar.read@user',
    'aura.calendar.write@user',
    'aura.messages.read@user',
    'aura.location.read@user',
    'aura.voice.command.execute@user',
    'aura.health.read@user',
    'aura.social.publish@user',
    'callstack.call.read@tenant',
    'callstack.call.write@tenant',
    'callstack.agent.admin@tenant',
)
